export const MEGA_CATALOG = [
  // =========================================================================
  // 1. COMPUTING & SMARTPHONES (Apple, Lenovo, Samsung, Dell, Asus, HP)
  // =========================================================================
  {
    sku: "COMP-APL-01",
    name: 'Apple MacBook Air 15" (M3, 16GB, 512GB)',
    category: "computing",
    subcategory: "laptops",
    tags: ["apple", "macbook", "laptop", "m3", "ultrabook", "macos", "lightweight", "computer"],
    price: 13490000,
    compare_at_price: 14490000,
    cost_price: 11000000,
    currency: "INR",
    in_stock: true,
    stock_count: 24,
    low_stock_threshold: 4,
    description: "Impossibly thin 15-inch Liquid Retina display with M3 chip, 18-hour battery life, and 1080p FaceTime HD camera.",
    short_pitch: "15.3-inch Liquid Retina display with 18-hour battery and fanless silent operation.",
    features: ["Apple M3 8-Core CPU & 10-Core GPU", "15.3-inch Liquid Retina Display", "18-Hour All-Day Battery", "MagSafe 3 Fast Charging"],
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80"],
    pairs_with: ["ACC-ANK-01", "LIFE-PKD-01", "STAT-GRV-01"],
    upgrades_to: "COMP-APL-02",
  },
  {
    sku: "COMP-APL-02",
    name: 'Apple MacBook Pro 16" (M3 Max, 36GB, 1TB)',
    category: "computing",
    subcategory: "laptops",
    tags: ["apple", "macbook pro", "laptop", "m3 max", "workstation", "creative", "computer"],
    price: 34990000,
    compare_at_price: 36990000,
    cost_price: 29000000,
    currency: "INR",
    in_stock: true,
    stock_count: 12,
    low_stock_threshold: 2,
    description: "The ultimate pro workstation laptop with M3 Max, Liquid Retina XDR display, up to 22 hours battery, and full array of pro ports.",
    short_pitch: "Extreme workstation performance with M3 Max and 120Hz ProMotion XDR display.",
    features: ["M3 Max 14-Core CPU & 30-Core GPU", "16.2-inch Liquid Retina XDR 120Hz", "HDMI, SDXC, and 3x Thunderbolt 4", "Up to 22 Hours Battery Life"],
    images: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "PER-DEL-01", "LIFE-PKD-01"],
  },
  {
    sku: "COMP-APL-03",
    name: "Apple iPhone 16 Pro Max (256GB, Natural Titanium)",
    category: "computing",
    subcategory: "phones",
    tags: ["apple", "iphone", "iphone 16 pro", "smartphone", "phone", "ios", "titanium"],
    price: 14490000,
    compare_at_price: 14990000,
    cost_price: 12200000,
    currency: "INR",
    in_stock: true,
    stock_count: 40,
    low_stock_threshold: 5,
    description: "Grade 5 titanium design with Camera Control button, 48MP Fusion camera, A18 Pro chip, and unprecedented battery longevity.",
    short_pitch: "A18 Pro chip, dedicated Camera Control button, and 48MP Fusion system.",
    features: ["A18 Pro Chip with 6-Core GPU", "Dedicated Tactile Camera Control", "6.9-inch Super Retina XDR ProMotion", "4K 120 fps Dolby Vision Recording"],
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80"],
    pairs_with: ["AUD-APL-01", "ACC-ANK-01"],
    upgrades_to: "COMP-APL-04",
  },
  {
    sku: "COMP-APL-04",
    name: 'Apple iPad Pro 13" (M4, 256GB, Ultra Retina XDR OLED)',
    category: "computing",
    subcategory: "tablets",
    tags: ["apple", "ipad", "ipad pro", "tablet", "m4", "oled", "pencil", "creatives"],
    price: 12990000,
    compare_at_price: 13990000,
    cost_price: 10500000,
    currency: "INR",
    in_stock: true,
    stock_count: 20,
    low_stock_threshold: 4,
    description: "Thinnest Apple product ever at 5.1mm with revolutionary tandem OLED Ultra Retina XDR display, breakthrough M4 performance, and Apple Pencil Pro support.",
    short_pitch: "5.1mm ultra-thin chassis with breakthrough M4 chip and tandem OLED display.",
    features: ["Breakthrough M4 Chip with 38 TOPS NPU", "13-inch Ultra Retina XDR Tandem OLED", "Thinnest Apple Design Ever (5.1mm)", "Supports Apple Pencil Pro & Magic Keyboard"],
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80"],
    pairs_with: ["ACC-ANK-01", "LIFE-PKD-01"],
  },
  {
    sku: "COMP-LNV-01",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    category: "computing",
    subcategory: "laptops",
    tags: ["lenovo", "lenevo", "thinkpad", "laptop", "intel core ultra", "business", "enterprise", "computer"],
    price: 16990000,
    compare_at_price: 18990000,
    cost_price: 13500000,
    currency: "INR",
    in_stock: true,
    stock_count: 18,
    low_stock_threshold: 3,
    description: "Ultralight carbon-fiber business laptop powered by Intel Core Ultra 7 with vPro, famous ergonomic keyboard, and MIL-SPEC durability.",
    short_pitch: "Legendary 1.09kg carbon-fiber enterprise ultrabook with Intel Core Ultra.",
    features: ["Intel Core Ultra 7 155H with NPU", "14-inch 2.8K OLED 120Hz Display", "MIL-STD 810H Military-Grade Toughness", "Classic Ergonomic TrackPoint Keyboard"],
    images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "ACC-ANK-01", "LIFE-BEL-01"],
    upgrades_to: "COMP-LNV-02",
  },
  {
    sku: "COMP-LNV-02",
    name: 'Lenovo Legion Pro 7i 16" Gaming Laptop',
    category: "computing",
    subcategory: "laptops",
    tags: ["lenovo", "lenevo", "legion", "gaming laptop", "rtx 4080", "high performance", "computer", "intel i9"],
    price: 24990000,
    compare_at_price: 27990000,
    cost_price: 20500000,
    currency: "INR",
    in_stock: true,
    stock_count: 10,
    low_stock_threshold: 2,
    description: "AI-tuned gaming powerhouse with Intel Core i9-14900HX, NVIDIA GeForce RTX 4080 12GB, and 240Hz PureSight Gaming display.",
    short_pitch: "Intel Core i9 + RTX 4080 with 240Hz display and Coldfront 5.0 vapor chamber cooling.",
    features: ["Intel Core i9-14900HX 24-Core", "NVIDIA RTX 4080 12GB GDDR6 175W", "16-inch WQXGA 240Hz 500 nits", "Legion Coldfront 5.0 Vapor Chamber"],
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80"],
    pairs_with: ["PER-KEY-01", "PER-LOG-01", "AUD-SNY-01"],
  },
  {
    sku: "COMP-LNV-03",
    name: "Lenovo Yoga 9i 2-in-1 Dual 4K OLED Laptop",
    category: "computing",
    subcategory: "laptops",
    tags: ["lenovo", "lenevo", "yoga", "2-in-1", "dual screen", "oled", "touchscreen", "creative"],
    price: 18490000,
    compare_at_price: 20990000,
    cost_price: 14800000,
    currency: "INR",
    in_stock: true,
    stock_count: 14,
    low_stock_threshold: 3,
    description: "Revolutionary convertible dual 13.3-inch PureSight OLED displays with Bowers & Wilkins rotating soundbar hinge and smart stylus.",
    short_pitch: "Dual 13.3-inch OLED touchscreens with rotating 360-degree soundbar hinge.",
    features: ["Dual 2.8K PureSight OLED Displays", "Bowers & Wilkins 360° Soundbar Hinge", "Intel Core Ultra 7 with Intel AI Boost", "Detachable Bluetooth Keyboard & Pen"],
    images: ["https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&q=80"],
    pairs_with: ["PER-LOG-02", "ACC-ANK-01"],
  },
  {
    sku: "COMP-SAM-01",
    name: 'Samsung Galaxy Book4 Pro 360 16"',
    category: "computing",
    subcategory: "laptops",
    tags: ["samsung", "galaxy book", "2-in-1", "laptop", "touchscreen", "s-pen", "oled"],
    price: 17990000,
    compare_at_price: 19990000,
    cost_price: 14500000,
    currency: "INR",
    in_stock: true,
    stock_count: 15,
    low_stock_threshold: 3,
    description: "2-in-1 convertible laptop with 16-inch 3K Dynamic AMOLED 2X touchscreen, bundled S Pen, and Intel Core Ultra 7 processor.",
    short_pitch: "Convertible 3K AMOLED 2X touchscreen with bundled precision S Pen.",
    features: ["16-inch 3K Dynamic AMOLED 2X 120Hz", "360° Rotating Hinge with S Pen", "Intel Core Ultra 7 155H Processor", "Seamless Galaxy Ecosystem Phone Link"],
    images: ["https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80"],
    pairs_with: ["COMP-SAM-02", "ACC-ANK-01"],
  },
  {
    sku: "COMP-SAM-02",
    name: "Samsung Galaxy S24 Ultra (512GB, Titanium)",
    category: "computing",
    subcategory: "phones",
    tags: ["samsung", "galaxy", "smartphone", "phone", "s24 ultra", "android", "titanium"],
    price: 13999000,
    compare_at_price: 14999000,
    cost_price: 11500000,
    currency: "INR",
    in_stock: true,
    stock_count: 35,
    low_stock_threshold: 5,
    description: "Titanium chassis with 200MP camera system, flat 6.8-inch Dynamic AMOLED 2X display, built-in S Pen, and Galaxy AI capabilities.",
    short_pitch: "200MP quad telephoto camera, titanium frame, and built-in S Pen with Galaxy AI.",
    features: ["200MP Ultra-Clear Quad Telephoto System", "Corning Gorilla Armor Anti-Reflective Glass", "Snapdragon 8 Gen 3 for Galaxy", "Built-In S Pen Stylus"],
    images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80"],
    pairs_with: ["AUD-SAM-01", "ACC-ANK-01"],
  },
  {
    sku: "COMP-SAM-03",
    name: "Samsung Galaxy Z Fold 6 (512GB, Phantom Silver)",
    category: "computing",
    subcategory: "phones",
    tags: ["samsung", "galaxy fold", "foldable", "smartphone", "phone", "z fold 6"],
    price: 17699900,
    compare_at_price: 18999900,
    cost_price: 14200000,
    currency: "INR",
    in_stock: true,
    stock_count: 16,
    low_stock_threshold: 3,
    description: "Ultra-slim foldable smartphone opening into a 7.6-inch tablet display with enhanced armor aluminum hinge and multi-window productivity.",
    short_pitch: "7.6-inch expansive folding screen with Galaxy AI dual-screen interpreter.",
    features: ["7.6-inch Dynamic AMOLED 2X Foldable Display", "Slim & Light Dual-Rail Hinge Design", "Snapdragon 8 Gen 3 Accelerated Gaming", "IP48 Water & Dust Resistance"],
    images: ["https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80"],
    pairs_with: ["ACC-ANK-01", "AUD-SAM-01"],
  },
  {
    sku: "COMP-DEL-01",
    name: 'Dell XPS 15 (OLED, Intel Core i7, 32GB)',
    category: "computing",
    subcategory: "laptops",
    tags: ["dell", "xps", "laptop", "oled", "creative", "windows", "computer"],
    price: 19490000,
    compare_at_price: 21990000,
    cost_price: 15800000,
    currency: "INR",
    in_stock: true,
    stock_count: 14,
    low_stock_threshold: 3,
    description: "Precision CNC machined aluminum chassis with carbon fiber palm rest, 3.5K OLED InfinityEdge touch display, and NVIDIA RTX 4060.",
    short_pitch: "3.5K OLED InfinityEdge display with CNC aluminum chassis and RTX 4060 graphics.",
    features: ["15.6-inch 3.5K OLED Touch 400 nits", "NVIDIA GeForce RTX 4060 8GB", "CNC Machined Aluminum Body", "Quad-Speaker Studio Sound Waves Nx"],
    images: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "LIFE-BEL-01"],
  },
  {
    sku: "COMP-ASU-01",
    name: "Asus ROG Zephyrus G16 (OLED 240Hz, RTX 4080)",
    category: "computing",
    subcategory: "laptops",
    tags: ["asus", "rog", "gaming laptop", "zephyrus", "oled", "rtx 4080", "computer"],
    price: 22999000,
    compare_at_price: 25999000,
    cost_price: 18900000,
    currency: "INR",
    in_stock: true,
    stock_count: 11,
    low_stock_threshold: 2,
    description: "CNC aluminum ultra-portable gaming laptop featuring 2.5K 240Hz ROG Nebula OLED display, Intel Core Ultra 9, and Slash Lighting lid.",
    short_pitch: "1.85kg sleek aluminum gamer with 240Hz OLED and RTX 4080 graphics.",
    features: ["2.5K 240Hz 0.2ms OLED ROG Nebula Display", "NVIDIA RTX 4080 12GB Laptop GPU", "Intel Core Ultra 9 185H with AI Acceleration", "Customizable Slash Lighting Lid Matrix"],
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80"],
    pairs_with: ["PER-LOG-04", "AUD-SNY-01"],
  },

  // =========================================================================
  // 2. LOGITECH & WORKSPACE PERIPHERALS ("glotech", Logitech, Keychron, Razer, Anker)
  // =========================================================================
  {
    sku: "PER-LOG-01",
    name: "Logitech MX Master 3S Wireless Performance Mouse",
    category: "accessories",
    subcategory: "mice",
    tags: ["logitech", "glotech", "mx master", "mouse", "wireless mouse", "ergonomic", "accessories"],
    price: 999500,
    compare_at_price: 1199500,
    cost_price: 650000,
    currency: "INR",
    in_stock: true,
    stock_count: 35,
    low_stock_threshold: 5,
    description: "The gold standard productivity mouse with 8000 DPI Darkfield glass tracking, MagSpeed electromagnetic scroll wheel, and 90% quieter clicks.",
    short_pitch: "MagSpeed electromagnetic scroll wheel with 8000 DPI track-on-glass sensor.",
    features: ["MagSpeed Electromagnetic Scrolling (1000 lines/sec)", "8000 DPI Optical Sensor Tracks on Any Glass", "Quiet Clicks Reduce 90% Click Noise", "Flow Cross-Computer Control Across 3 Devices"],
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80"],
    pairs_with: ["PER-KEY-01", "STAT-GRV-01"],
  },
  {
    sku: "PER-LOG-02",
    name: "Logitech MX Anywhere 3S Compact Wireless Mouse",
    category: "accessories",
    subcategory: "mice",
    tags: ["logitech", "glotech", "mouse", "wireless mouse", "travel mouse", "portable", "compact"],
    price: 749500,
    compare_at_price: 899500,
    cost_price: 480000,
    currency: "INR",
    in_stock: true,
    stock_count: 40,
    low_stock_threshold: 6,
    description: "Pocket-sized ergonomic mouse with 8K DPI sensor that tracks on glass, MagSpeed scrolling, and 70-day battery life for commuters and travelers.",
    short_pitch: "Ultra-portable 8K DPI mouse designed for mobile workstations and café setups.",
    features: ["8000 DPI Sensor Tracks on Any Surface Even Glass", "MagSpeed Precision Scrolling", "Quiet Click Architecture", "Up to 70 Days on Full Charge via USB-C"],
    images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "LIFE-BEL-01"],
    upgrades_to: "PER-LOG-01",
  },
  {
    sku: "PER-LOG-03",
    name: "Logitech MX Mechanical Wireless Illuminated Keyboard",
    category: "accessories",
    subcategory: "keyboards",
    tags: ["logitech", "glotech", "keyboard", "mechanical keyboard", "wireless", "ergonomic"],
    price: 1549500,
    compare_at_price: 1799500,
    cost_price: 1050000,
    currency: "INR",
    in_stock: true,
    stock_count: 25,
    low_stock_threshold: 4,
    description: "Low-profile mechanical keyboard with tactile quiet switches, smart backlighting that illuminates as hands approach, and dual Mac/Windows keycaps.",
    short_pitch: "Low-profile tactile quiet mechanical switches with hand-proximity backlighting.",
    features: ["Low-Profile Tactile Quiet Mechanical Switches", "Smart Backlighting Detects Hand Proximity", "Multi-Device Easy-Switch for 3 Systems", "USB-C Fast Rechargeable Battery"],
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "STAT-GRV-01"],
  },
  {
    sku: "PER-LOG-04",
    name: "Logitech G Pro X Superlight 2 Wireless Gaming Mouse",
    category: "accessories",
    subcategory: "mice",
    tags: ["logitech", "glotech", "gaming mouse", "esports", "wireless mouse", "lightweight"],
    price: 1499500,
    compare_at_price: 1699500,
    cost_price: 980000,
    currency: "INR",
    in_stock: true,
    stock_count: 22,
    low_stock_threshold: 4,
    description: "Esports championship standard 60g ultralight mouse with HERO 2 sensor (32,000 DPI, 500+ IPS), LIGHTFORCE hybrid optical switches, and 95hr battery.",
    short_pitch: "60-gram esports mouse with HERO 2 sensor and LIGHTFORCE optical switches.",
    features: ["60g Featherweight Esports Chassis", "HERO 2 Sensor with 32,000 DPI & 4K Polling", "LIGHTFORCE Hybrid Optical-Mechanical Switches", "Zero-Additive PTFE Glides for Frictionless Glide"],
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80"],
    pairs_with: ["COMP-LNV-02", "AUD-SNY-01"],
  },
  {
    sku: "PER-LOG-05",
    name: "Logitech Brio 4K Ultra HD Pro Webcam",
    category: "accessories",
    subcategory: "webcams",
    tags: ["logitech", "glotech", "webcam", "4k webcam", "streaming", "video calls", "zoom"],
    price: 1799500,
    compare_at_price: 2199500,
    cost_price: 1180000,
    currency: "INR",
    in_stock: true,
    stock_count: 19,
    low_stock_threshold: 3,
    description: "Premier 4K HDR webcam with RightLight 3 light correction, dual omnidirectional noise-cancelling microphones, and Windows Hello facial recognition.",
    short_pitch: "4K HDR webcam with RightLight 3 auto-exposure and Windows Hello infrared login.",
    features: ["Ultra 4K HD at 30 fps or 1080p at 60 fps", "RightLight 3 with HDR for Any Lighting Condition", "Infrared Facial Recognition Windows Hello", "Adjustable Field of View (65°, 78°, 90°)"],
    images: ["https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&q=80"],
    pairs_with: ["STAT-GRV-01", "PER-LOG-01"],
  },
  {
    sku: "PER-KEY-01",
    name: "Keychron Q1 Pro Wireless Custom Mechanical Keyboard",
    category: "accessories",
    subcategory: "keyboards",
    tags: ["keychron", "mechanical keyboard", "keyboard", "wireless", "custom", "accessories"],
    price: 1899900,
    compare_at_price: 2199900,
    cost_price: 1250000,
    currency: "INR",
    in_stock: true,
    stock_count: 20,
    low_stock_threshold: 4,
    description: "Full CNC machined 6063 aluminum body 75% keyboard with double-gasket design, hot-swappable switches, wireless Bluetooth 5.1, and QMK/VIA support.",
    short_pitch: "Full CNC aluminum 75% mechanical keyboard with double-gasket mount and Bluetooth.",
    features: ["Solid 6063 Aluminum CNC Machined Body", "Double-Gasket Acoustic Sound Dampening", "Hot-Swappable K Pro Mechanical Switches", "Fully Programmable with QMK & VIA Web App"],
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "STAT-GRV-01"],
  },
  {
    sku: "PER-RAZ-01",
    name: "Razer DeathAdder V3 Pro Wireless Ergonomic Gaming Mouse",
    category: "accessories",
    subcategory: "mice",
    tags: ["razer", "gaming mouse", "deathadder", "wireless mouse", "esports", "accessories"],
    price: 1399900,
    compare_at_price: 1599900,
    cost_price: 920000,
    currency: "INR",
    in_stock: true,
    stock_count: 24,
    low_stock_threshold: 4,
    description: "Iconic ergonomic shape refined with top esports pros. 63g ultra-lightweight, Focus Pro 30K optical sensor, and Gen-3 optical mouse switches.",
    short_pitch: "63g ergonomic esports mouse with 30K optical sensor and zero double-click issues.",
    features: ["Focus Pro 30K Optical Sensor with 99.8% Accuracy", "63g Ultra-Lightweight Ergonomic Form", "Gen-3 Optical Switches (90M Click Durability)", "HyperSpeed Wireless Low Latency Connection"],
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80"],
    pairs_with: ["COMP-ASU-01", "COMP-LNV-02"],
  },
  {
    sku: "ACC-ANK-01",
    name: "Anker Prime 100W GaN 3-Port Fast Wall Charger",
    category: "accessories",
    subcategory: "chargers",
    tags: ["anker", "charger", "gan", "fast charging", "usb-c", "power", "accessories"],
    price: 599900,
    compare_at_price: 749900,
    cost_price: 360000,
    currency: "INR",
    in_stock: true,
    stock_count: 50,
    low_stock_threshold: 10,
    description: "Ultra-compact GaNPrime wall charger powering up to 3 devices simultaneously with 100W maximum single-port power for MacBooks, ThinkPads, and phones.",
    short_pitch: "100W GaN 3-port pocket-sized fast charger for laptops, tablets, and phones.",
    features: ["100W Max Single-Port Fast Power Delivery", "GaNPrime Energy-Efficient Architecture", "Powers 2 Laptops and 1 Phone Simultaneously", "ActiveShield 2.0 Temperature Monitoring"],
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "COMP-LNV-01", "COMP-SAM-02"],
    upgrades_to: "ACC-ANK-02",
  },
  {
    sku: "ACC-ANK-02",
    name: "Anker Prime 20,000mAh Power Bank (200W Output, Smart Display)",
    category: "accessories",
    subcategory: "chargers",
    tags: ["anker", "power bank", "battery", "fast charging", "portable charger", "usb-c"],
    price: 1199900,
    compare_at_price: 1399900,
    cost_price: 760000,
    currency: "INR",
    in_stock: true,
    stock_count: 30,
    low_stock_threshold: 5,
    description: "High-capacity power bank delivering up to 200W total output with smart digital display showing remaining time, output wattage, and battery health.",
    short_pitch: "200W total output powerhouse charges two laptops simultaneously on the go.",
    features: ["200W Heavy-Duty Multi-Port Fast Output", "20,000mAh Laptop-Charging Capacity", "Smart Interactive Digital LCD Display", "Recharges to 100% in Just 1 Hour 15 Mins"],
    images: ["https://images.unsplash.com/photo-1609592424364-c4ca4d5d9c79?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "COMP-LNV-01"],
  },
  {
    sku: "PER-DEL-01",
    name: 'Dell UltraSharp 32" 4K Curved USB-C Hub Monitor (U3224KB)',
    category: "computing",
    subcategory: "monitors",
    tags: ["dell", "ultrasharp", "monitor", "4k monitor", "usb-c hub", "display", "workspace"],
    price: 8999900,
    compare_at_price: 9999900,
    cost_price: 7200000,
    currency: "INR",
    in_stock: true,
    stock_count: 8,
    low_stock_threshold: 2,
    description: "Premier 32-inch 6K/4K IPS Black monitor with built-in 4K dual-gain HDR webcam, Thunderbolt 4 140W power delivery, and 2000:1 contrast ratio.",
    short_pitch: "IPS Black 2000:1 contrast monitor with 140W Thunderbolt 4 hub and 4K HDR webcam.",
    features: ["IPS Black Panel with 2000:1 Deep Contrast", "Thunderbolt 4 Hub with 140W Power Delivery", "Built-In 4K HDR Webcam & Echo-Cancelling Mics", "99% DCI-P3 Professional Color Accuracy"],
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "COMP-APL-02", "PER-LOG-01"],
  },

  // =========================================================================
  // 3. HOME APPLIANCES (Fridges, Washing Machines, Cleaning, Climate)
  // =========================================================================
  {
    sku: "APP-SAM-01",
    name: "Samsung 653L Side-by-Side Smart Refrigerator with AI Inverter",
    category: "appliances",
    subcategory: "refrigerators",
    tags: ["samsung", "refrigerator", "fridge", "firdge", "appliances", "smart home", "kitchen"],
    price: 8499000,
    compare_at_price: 9999000,
    cost_price: 6400000,
    currency: "INR",
    in_stock: true,
    stock_count: 8,
    low_stock_threshold: 2,
    description: "Spacious 653L SpaceMax refrigerator with convertible 5-in-1 modes, Digital Inverter compressor with 20-year warranty, and SmartThings WiFi monitoring.",
    short_pitch: "653L SpaceMax side-by-side with SmartThings AI Energy mode and 20yr warranty.",
    features: ["653 Litre Massive SpaceMax Capacity", "SmartThings AI Energy Mode (Up to 10% Savings)", "Twin Cooling Plus Independent Evaporators", "Convertible 5-in-1 Storage Flex"],
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&q=80"],
    pairs_with: ["APP-PHL-01"],
    upgrades_to: "APP-SAM-02",
  },
  {
    sku: "APP-SAM-02",
    name: "Samsung 670L French Door Family Hub Smart Refrigerator",
    category: "appliances",
    subcategory: "refrigerators",
    tags: ["samsung", "refrigerator", "fridge", "firdge", "family hub", "touchscreen", "smart home", "luxury"],
    price: 18999000,
    compare_at_price: 21999000,
    cost_price: 14800000,
    currency: "INR",
    in_stock: true,
    stock_count: 5,
    low_stock_threshold: 1,
    description: "Flagship French door refrigerator with built-in 21.5-inch touchscreen Family Hub, internal cameras to view groceries from your phone, and beverage center.",
    short_pitch: "21.5-inch touchscreen Family Hub, inside cameras, and automatic beverage center.",
    features: ["21.5-inch Touchscreen Family Hub", "View Inside Groceries Camera from Phone", "AutoFill Water Pitcher with Flavor Infuser", "Triple Cooling Independent Temperature Zones"],
    images: ["https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80"],
    pairs_with: ["APP-PHL-01"],
  },
  {
    sku: "APP-LG-01",
    name: "LG 9kg AI Direct Drive Front Load Washing Machine",
    category: "appliances",
    subcategory: "washing-machines",
    tags: ["lg", "washing machine", "washmings", "washer", "front load", "appliances", "laundry", "smart home"],
    price: 4499000,
    compare_at_price: 5299000,
    cost_price: 3400000,
    currency: "INR",
    in_stock: true,
    stock_count: 12,
    low_stock_threshold: 3,
    description: "Intelligent fabric care with AI DD motor that weighs laundry and detects fabric softness, Steam+ allergy care, and TurboWash 360 in 39 minutes.",
    short_pitch: "AI DD intelligent fabric protection with Steam+ allergy care and TurboWash 360.",
    features: ["AI DD Smart Motor Detects Fabric Softness", "Steam+ Eliminates 99.9% of Allergens", "TurboWash 360 Completes in 39 Mins", "LG ThinQ WiFi Remote Control"],
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&q=80"],
    pairs_with: ["APP-DYS-01"],
  },
  {
    sku: "APP-LG-02",
    name: "LG 655L Frost Free Inverter Side-by-Side Refrigerator",
    category: "appliances",
    subcategory: "refrigerators",
    tags: ["lg", "refrigerator", "fridge", "firdge", "side by side", "appliances", "smart inverter", "kitchen"],
    price: 8799000,
    compare_at_price: 9999000,
    cost_price: 6700000,
    currency: "INR",
    in_stock: true,
    stock_count: 7,
    low_stock_threshold: 2,
    description: "DoorCooling+ delivers even cooling throughout the cabinet, Multi Air Flow digital sensors maintain optimal temperature, Smart Inverter Compressor.",
    short_pitch: "DoorCooling+ with Multi Air Flow and Smart Inverter compressor with 10yr warranty.",
    features: ["655 Litres Expansive Storage", "DoorCooling+ Air Vents Along Door Frame", "Multi Air Flow Digital Temperature Control", "Smart Diagnosis via LG ThinQ App"],
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&q=80"],
    pairs_with: ["APP-LG-01"],
  },
  {
    sku: "APP-BOS-01",
    name: "Bosch 9kg Series 8 Front Load Washing Machine",
    category: "appliances",
    subcategory: "washing-machines",
    tags: ["bosch", "washing machine", "washmings", "washer", "appliances", "german engineering", "laundry"],
    price: 5499000,
    compare_at_price: 6399000,
    cost_price: 4100000,
    currency: "INR",
    in_stock: true,
    stock_count: 10,
    low_stock_threshold: 2,
    description: "German-engineered Series 8 washer with ActiveOxygen hygienic washing at low temperatures, EcoSilence Drive brushless motor, and AntiStain automatic system.",
    short_pitch: "ActiveOxygen removes 99.99% of bacteria without chemicals; EcoSilence Drive.",
    features: ["ActiveOxygen Eliminates 99.99% of Bacteria", "EcoSilence Drive Ultra-Quiet Frictionless Motor", "AntiStain Automatically Targets 4 Stubborn Stains", "SpeedPerfect Reduces Cycle Time by Up to 65%"],
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&q=80"],
    pairs_with: ["APP-DYS-01"],
  },
  {
    sku: "APP-WHR-01",
    name: "Whirlpool 570L Inverter Multi-Door Frost Free Refrigerator",
    category: "appliances",
    subcategory: "refrigerators",
    tags: ["whirlpool", "refrigerator", "fridge", "firdge", "multi door", "appliances", "kitchen"],
    price: 6899000,
    compare_at_price: 7999000,
    cost_price: 5200000,
    currency: "INR",
    in_stock: true,
    stock_count: 9,
    low_stock_threshold: 2,
    description: "Adaptive Intelligence technology continuously senses, adapts, and controls temperature inside, featuring moisture lock crisper and holiday mode.",
    short_pitch: "Adaptive Intelligence microprocessor senses load and weather to optimize cooling.",
    features: ["570L Triple Door Architecture", "Adaptive Intelligence Temperature Tuning", "Microblock Technology Prevents 99% Bacterial Growth", "Feather Touch Digital Control Panel"],
    images: ["https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80"],
    pairs_with: ["APP-PHL-01"],
  },
  {
    sku: "APP-DYS-01",
    name: "Dyson V15 Detect Absolute Cordless Vacuum Cleaner",
    category: "appliances",
    subcategory: "cleaning",
    tags: ["dyson", "vacuum", "cordless vacuum", "cleaning", "appliances", "smart home"],
    price: 6290000,
    compare_at_price: 6990000,
    cost_price: 4800000,
    currency: "INR",
    in_stock: true,
    stock_count: 15,
    low_stock_threshold: 3,
    description: "Most powerful intelligent cordless vacuum with laser illumination revealing microscopic dust, acoustic piezo sensor, and anti-tangle Hair Screw tool.",
    short_pitch: "Laser dust detection, 240AW hyperdymium suction, and real-time particle LCD count.",
    features: ["Green Laser Reveals Invisible Microscopic Dust", "Piezo Sensor Counts & Sizes Dust Particles", "Up to 60 Minutes of Fade-Free Suction", "Hair Screw Tool Removes Pet Hair Instantly"],
    images: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80"],
    pairs_with: ["APP-DYS-02"],
  },
  {
    sku: "APP-DYS-02",
    name: "Dyson Purifier Hot+Cool Gen1 Air Purifier & Heater",
    category: "appliances",
    subcategory: "air-purifiers",
    tags: ["dyson", "air purifier", "heater", "appliances", "smart home", "climate"],
    price: 4690000,
    compare_at_price: 5490000,
    cost_price: 3600000,
    currency: "INR",
    in_stock: true,
    stock_count: 18,
    low_stock_threshold: 3,
    description: "Fully sealed HEPA H13 filtration capturing 99.95% of pollutants as small as 0.1 microns, combined with fast long-range room heating and cooling fan.",
    short_pitch: "HEPA H13 sealed air purifier with ceramic room heating and powerful cooling fan.",
    features: ["HEPA H13 Traps 99.95% of Particles to 0.1 Microns", "Fast Room Heating with Ceramic Plates", "Air Multiplier Technology Circulates Whole Room", "Real-Time Air Quality Sensor Reports"],
    images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80"],
    pairs_with: ["APP-DYS-01"],
  },
  {
    sku: "APP-PHL-01",
    name: "Philips Smart Digital Air Fryer XXL 7.2L",
    category: "appliances",
    subcategory: "kitchen",
    tags: ["philips", "air fryer", "kitchen", "appliances", "healthy cooking", "smart"],
    price: 1499900,
    compare_at_price: 1899900,
    cost_price: 950000,
    currency: "INR",
    in_stock: true,
    stock_count: 28,
    low_stock_threshold: 5,
    description: "Rapid Air technology with unique starfish design for 90% less fat cooking, generous 7.2L basket, and NutriU smart recipe app integration.",
    short_pitch: "7.2L family capacity with Rapid Air technology and 16 pre-set cooking programs.",
    features: ["Rapid Air Starfish Technology", "7.2 Litre XXL Family Capacity (1.4kg Fries)", "Cooks with Up to 90% Less Fat", "NutriU App Connected Recipes"],
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80"],
    pairs_with: ["APP-SAM-01"],
  },

  // =========================================================================
  // 4. STATIONERY & EXECUTIVE DESK GEAR (Parker, Lamy, Pilot, Moleskine, Grovemade)
  // =========================================================================
  {
    sku: "STAT-PRK-01",
    name: "Parker Sonnet Fountain Pen (18K Solid Gold Nib, Lacquer Black)",
    category: "stationery",
    subcategory: "pens",
    tags: ["parker", "fountain pen", "pen", "stationery", "stationary", "luxury", "executive", "writing"],
    price: 1849900,
    compare_at_price: 2199900,
    cost_price: 1200000,
    currency: "INR",
    in_stock: true,
    stock_count: 20,
    low_stock_threshold: 4,
    description: "Timeless symbol of elegance hand-assembled with 17 individual pieces, 18k solid gold rhodium-finish nib, and deep gloss black lacquer finish.",
    short_pitch: "Hand-crafted 18k solid gold nib with deep black gloss lacquer and palladium trims.",
    features: ["18-Karat Solid Gold Nib Hand-Finished", "High-Gloss Black Lacquer Finish", "Piston Fill Converter & Quink Ink Cartridges", "Presented in Parker Luxury Gift Box"],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&q=80"],
    pairs_with: ["STAT-MOL-01", "STAT-GRV-01"],
    upgrades_to: "STAT-LAM-01",
  },
  {
    sku: "STAT-PRK-02",
    name: "Parker 51 Deluxe Fountain Pen (Plum with Chiseled Gold Cap)",
    category: "stationery",
    subcategory: "pens",
    tags: ["parker", "fountain pen", "pen", "stationery", "stationary", "vintage", "writing", "executive"],
    price: 2499900,
    compare_at_price: 2799900,
    cost_price: 1650000,
    currency: "INR",
    in_stock: true,
    stock_count: 14,
    low_stock_threshold: 3,
    description: "Modern reimagining of the world's most wanted pen first launched in 1941. Features 18k gold hooded nib and precious plum resin barrel.",
    short_pitch: "Iconic 1941 silhouette with 18k gold hooded nib and laser-chiseled cap.",
    features: ["18-Karat Gold Hooded Nib Prevents Ink Drying", "Precious Gloss Plum Resin Barrel", "Cap Chiseled with Geometric Grid Pattern", "Screw-Close Protective Cap Mechanism"],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&q=80"],
    pairs_with: ["STAT-MOL-01"],
  },
  {
    sku: "STAT-LAM-01",
    name: "Lamy 2000 Makrolon Fountain Pen (14K Gold Nib)",
    category: "stationery",
    subcategory: "pens",
    tags: ["lamy", "fountain pen", "pen", "stationery", "stationary", "bauhaus", "writing", "executive"],
    price: 2199900,
    compare_at_price: 2499900,
    cost_price: 1500000,
    currency: "INR",
    in_stock: true,
    stock_count: 15,
    low_stock_threshold: 3,
    description: "Bauhaus design icon in continuous production since 1966. Made from brushed fiberglass Makrolon with platinum-coated 14k gold hooded nib and piston filling.",
    short_pitch: "1966 Bauhaus design icon in seamless brushed Makrolon fiberglass.",
    features: ["14-Karat Gold Platinum-Coated Hooded Nib", "Brushed Makrolon Fiberglass Body", "Built-In Smooth Piston Mechanism", "Spring-Loaded Solid Stainless Steel Clip"],
    images: ["https://images.unsplash.com/photo-1585336261026-40742f36f901?w=800&q=80"],
    pairs_with: ["STAT-MOL-01"],
  },
  {
    sku: "STAT-PLT-01",
    name: "Pilot Custom 823 Amber Fountain Pen (14K Gold Nib, Vacuum Filler)",
    category: "stationery",
    subcategory: "pens",
    tags: ["pilot", "fountain pen", "pen", "stationery", "stationary", "japanese", "writing", "luxury"],
    price: 2899900,
    compare_at_price: 3299900,
    cost_price: 1980000,
    currency: "INR",
    in_stock: true,
    stock_count: 12,
    low_stock_threshold: 3,
    description: "Revered as one of the smoothest writing instruments on earth. Translucent amber demonstrator with high-capacity plunger vacuum filling system and 14k Pilot #15 gold nib.",
    short_pitch: "Translucent amber vacuum demonstrator with legendary ultra-smooth Pilot #15 14k nib.",
    features: ["14-Karat Solid Gold Pilot Size #15 Nib", "High-Capacity Vacuum Plunger Filling System", "Translucent Amber Acrylic Demonstrator Body", "Shut-Off Valve for Safe Airplane Travel"],
    images: ["https://images.unsplash.com/photo-1585336261026-40742f36f901?w=800&q=80"],
    pairs_with: ["STAT-MOL-01", "STAT-GRV-01"],
  },
  {
    sku: "STAT-MOL-01",
    name: "Moleskine Classic Expanded Hardcover Notebook (Dotted, Large)",
    category: "stationery",
    subcategory: "notebooks",
    tags: ["moleskine", "notebook", "journal", "stationery", "stationary", "paper", "writing"],
    price: 249900,
    compare_at_price: 299900,
    cost_price: 120000,
    currency: "INR",
    in_stock: true,
    stock_count: 60,
    low_stock_threshold: 10,
    description: "Expanded 400-page version of the legendary notebook with acid-free ivory paper, expandable inner pocket, ribbon bookmark, and elastic closure band.",
    short_pitch: "400 pages of 70 gsm ivory acid-free dotted paper with lay-flat binding.",
    features: ["400 Pages of Dotted Ivory Paper (70 gsm)", "Durable Oilcloth-Bound Hardcover", "Expandable Inner Accordion Pocket", "Thread-Bound to Open Perfectly Flat 180°"],
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80"],
    pairs_with: ["STAT-PRK-01", "STAT-LAM-01"],
    upgrades_to: "STAT-MOL-02",
  },
  {
    sku: "STAT-MOL-02",
    name: "Moleskine Smart Writing Set 2.0 (Smart Pen + Paper Tablet)",
    category: "stationery",
    subcategory: "notebooks",
    tags: ["moleskine", "smart pen", "notebook", "digital note taking", "stationery", "stationary", "writing"],
    price: 1999900,
    compare_at_price: 2299900,
    cost_price: 1350000,
    currency: "INR",
    in_stock: true,
    stock_count: 18,
    low_stock_threshold: 4,
    description: "Instantly digitize your handwritten notes and sketches in real time as you write on paper to your iPhone, iPad, or Android device using the Smart Pen and Ncoded paper.",
    short_pitch: "Digitizes real-time pen-on-paper strokes to your phone or tablet instantly.",
    features: ["Smart Pen Captures Real-Time Vector Strokes", "Specially Coded Ncode Paper Tablet Notebook", "Moleskine Notes App Real-Time Transcription", "Audio Recording Synced with Written Notes"],
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80"],
    pairs_with: ["COMP-APL-04", "COMP-APL-03"],
  },
  {
    sku: "STAT-GRV-01",
    name: "Grovemade Walnut & Aluminum Dual Desk Shelf",
    category: "stationery",
    subcategory: "desk-organizers",
    tags: ["grovemade", "desk shelf", "desk stand", "walnut", "workspace", "ergonomics", "stationery", "stationary"],
    price: 2699900,
    compare_at_price: 3199900,
    cost_price: 1750000,
    currency: "INR",
    in_stock: true,
    stock_count: 10,
    low_stock_threshold: 2,
    description: "Handcrafted American Black Walnut desk organizer shelf with solid 5052 curved aluminum tray, raising two monitors to ergonomic eye level.",
    short_pitch: "American Black Walnut dual monitor shelf with precision-bent aluminum shelf.",
    features: ["Solid American Black Walnut Hardwood", "Anodized 5052 Aluminum Accent Tray", "Elevates Dual Monitors to Ergonomic Eye Level", "Natural Cork Feet Prevent Desk Scratches"],
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80"],
    pairs_with: ["PER-LOG-01", "PER-KEY-01", "STAT-PRK-01"],
  },

  // =========================================================================
  // 5. LIFESTYLE, TRAVEL & BAGS (Peak Design, Bellroy, Yeti, Victorinox)
  // =========================================================================
  {
    sku: "LIFE-PKD-01",
    name: "Peak Design Everyday Backpack 30L V2 (Black)",
    category: "lifestyle",
    subcategory: "backpacks",
    tags: ["peak design", "backpack", "bag", "laptop bag", "camera bag", "travel", "lifestyle", "life stlye"],
    price: 2999900,
    compare_at_price: 3499900,
    cost_price: 1950000,
    currency: "INR",
    in_stock: true,
    stock_count: 18,
    low_stock_threshold: 3,
    description: "Award-winning iconic everyday backpack with MagLatch hardware, dual UltraZips, FlexFold dividers, and dedicated 16-inch laptop compartment.",
    short_pitch: "Weatherproof 400D recycled nylon shell with MagLatch and FlexFold origami dividers.",
    features: ["100% Recycled 400D Weatherproof Shell", "MagLatch Hardware for Instant One-Handed Access", "Configurable FlexFold Internal Dividers", "Holds Up to 16-inch Laptop and Tablet"],
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "LIFE-YET-01"],
  },
  {
    sku: "LIFE-BEL-01",
    name: "Bellroy Transit Workpack 20L (Water-Resistant)",
    category: "lifestyle",
    subcategory: "backpacks",
    tags: ["bellroy", "backpack", "commute", "laptop bag", "lifestyle", "life stlye", "travel"],
    price: 1899900,
    compare_at_price: 2199900,
    cost_price: 1250000,
    currency: "INR",
    in_stock: true,
    stock_count: 24,
    low_stock_threshold: 4,
    description: "Clean, streamlined daily commute backpack with separate padded 16-inch laptop pocket, hidden sunglasses pouch, and breathable contour back panel.",
    short_pitch: "Streamlined 20L commuter backpack with water-resistant Baida nylon fabric.",
    features: ["Separate External-Access Padded 16-inch Laptop Sleeve", "Soft-Lined Quick-Access Sunglasses Pouch", "Luggage Pass-Through Strap for Rolling Bags", "Water-Resistant Woven Recycled Fabric"],
    images: ["https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&q=80"],
    pairs_with: ["COMP-LNV-01", "LIFE-YET-01"],
    upgrades_to: "LIFE-PKD-01",
  },
  {
    sku: "LIFE-YET-01",
    name: "Yeti Rambler 36oz Vacuum Insulated Bottle with Chug Cap",
    category: "lifestyle",
    subcategory: "hydration",
    tags: ["yeti", "water bottle", "hydration", "travel", "insulated", "lifestyle", "life stlye"],
    price: 549900,
    compare_at_price: 649900,
    cost_price: 320000,
    currency: "INR",
    in_stock: true,
    stock_count: 45,
    low_stock_threshold: 8,
    description: "Indestructible 18/8 kitchen-grade stainless steel bottle with double-wall vacuum insulation keeping ice frozen for 36 hours. Shatter-resistant Chug Cap.",
    short_pitch: "Double-wall vacuum insulated 18/8 stainless steel keeps ice frozen for 36+ hours.",
    features: ["Double-Wall Vacuum Insulation Keeps Ice 36+ Hours", "18/8 Kitchen-Grade Stainless Steel Resists Dents", "100% Leakproof TripleHaul Chug Cap", "Dishwasher Safe with DuraCoat Color Finish"],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80"],
    pairs_with: ["LIFE-BEL-01", "LIFE-PKD-01"],
  },
  {
    sku: "LIFE-VIC-01",
    name: "Victorinox Swiss Army SwissChamp XXL 73-Function Pocket Knife",
    category: "lifestyle",
    subcategory: "edc",
    tags: ["victorinox", "swiss army", "multitool", "edc", "knife", "lifestyle", "life stlye", "travel"],
    price: 2499900,
    compare_at_price: 2899900,
    cost_price: 1600000,
    currency: "INR",
    in_stock: true,
    stock_count: 15,
    low_stock_threshold: 3,
    description: "The ultimate collector's companion hand-crafted in Ibach, Switzerland. Packs 73 functions including pliers, precision bits, magnifying glass, and ruler into a compact red cellidor handle.",
    short_pitch: "73 functions hand-assembled in Switzerland for collectors and adventurers.",
    features: ["73 Precision Stainless Steel Functions", "Hand-Assembled in Ibach, Switzerland", "Includes Bit Wrench, Pliers, & Magnifying Lens", "Delivered in Luxury Presentation Gift Box"],
    images: ["https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=800&q=80"],
    pairs_with: ["LIFE-PKD-01"],
  },

  // =========================================================================
  // 6. AUDIO & ACOUSTICS (Sony, Bose, Apple, Marshall, JBL, Sennheiser)
  // =========================================================================
  {
    sku: "AUD-SNY-01",
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    category: "audio",
    subcategory: "headphones",
    tags: ["sony", "headphones", "anc", "noise cancelling", "wireless", "audio", "bluetooth"],
    price: 2999000,
    compare_at_price: 3499000,
    cost_price: 2100000,
    currency: "INR",
    in_stock: true,
    stock_count: 30,
    low_stock_threshold: 5,
    description: "Industry-leading noise cancellation with two processors and 8 microphones, LDAC Hi-Res Wireless audio, and 30-hour battery life.",
    short_pitch: "Industry-benchmark ANC with dual V1/QN1 chips and crystal-clear hands-free calls.",
    features: ["Dual Processor Active Noise Cancellation", "30-Hour Battery with 3-min Quick Charge", "LDAC High-Resolution Wireless Audio", "Speak-to-Chat Automatic Pausing"],
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80"],
    pairs_with: ["ACC-ANK-01", "STAT-GRV-01"],
    upgrades_to: "AUD-APL-02",
  },
  {
    sku: "AUD-BOS-01",
    name: "Bose QuietComfort Ultra Headphones",
    category: "audio",
    subcategory: "headphones",
    tags: ["bose", "headphones", "quietcomfort", "anc", "spatial audio", "wireless"],
    price: 3590000,
    compare_at_price: 3890000,
    cost_price: 2600000,
    currency: "INR",
    in_stock: true,
    stock_count: 22,
    low_stock_threshold: 4,
    description: "Breakthrough spatialized audio with world-class noise cancellation, CustomTune acoustic personalization, and ultra-luxurious protein leather cushions.",
    short_pitch: "World-class noise cancellation with Bose Immersive Spatial Audio.",
    features: ["Bose Immersive Audio Spatial Staging", "CustomTune Acoustic Calibration", "Quiet, Aware, and Immersion Modes", "24-Hour Battery Life"],
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80"],
    pairs_with: ["ACC-ANK-01"],
    upgrades_to: "AUD-APL-02",
  },
  {
    sku: "AUD-APL-01",
    name: "Apple AirPods Pro (2nd Generation, USB-C)",
    category: "audio",
    subcategory: "earbuds",
    tags: ["apple", "airpods", "earbuds", "anc", "wireless", "audio", "bluetooth"],
    price: 2490000,
    compare_at_price: 2690000,
    cost_price: 1900000,
    currency: "INR",
    in_stock: true,
    stock_count: 50,
    low_stock_threshold: 8,
    description: "Up to 2x more Active Noise Cancellation with H2 chip, Adaptive Audio, Transparency mode, and MagSafe charging case with Precision Finding.",
    short_pitch: "H2 chip with Adaptive Audio, Personalised Spatial Audio, and USB-C MagSafe case.",
    features: ["Apple H2 Audio Architecture", "Up to 2x Stronger Active Noise Cancellation", "Adaptive Audio Blends ANC & Transparency", "Dust, Sweat, and Water Resistant (IP54)"],
    images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80"],
    pairs_with: ["COMP-APL-03", "ACC-ANK-01"],
    upgrades_to: "AUD-APL-02",
  },
  {
    sku: "AUD-APL-02",
    name: "Apple AirPods Max (USB-C, Space Black)",
    category: "audio",
    subcategory: "headphones",
    tags: ["apple", "airpods max", "headphones", "anc", "luxury", "spatial audio"],
    price: 5990000,
    compare_at_price: 6490000,
    cost_price: 4600000,
    currency: "INR",
    in_stock: true,
    stock_count: 16,
    low_stock_threshold: 3,
    description: "Computational audio powered by Apple H1 chips in each cup, custom acoustic design, knit-mesh canopy, and anodized aluminum earcups.",
    short_pitch: "Masterful high-fidelity sound with acoustic mesh canopy and CNC aluminum cups.",
    features: ["Apple-Designed 40mm Dynamic Driver", "Computational Audio with Dual H1 Chips", "Lossless Audio over USB-C", "Stainless Steel Frame with Breathable Canopy"],
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80"],
    pairs_with: ["COMP-APL-01", "COMP-APL-03"],
  },
  {
    sku: "AUD-MAR-01",
    name: "Marshall Stanmore III Bluetooth Home Speaker",
    category: "audio",
    subcategory: "speakers",
    tags: ["marshall", "speaker", "bluetooth speaker", "home audio", "vintage", "sound"],
    price: 3799900,
    compare_at_price: 4199900,
    cost_price: 2700000,
    currency: "INR",
    in_stock: true,
    stock_count: 14,
    low_stock_threshold: 3,
    description: "Legendary rock 'n' roll home speaker with outward-angled tweeters, updated waveguides, and Dynamic Loudness tonal balance.",
    short_pitch: "80W home audio powerhouse with classic vintage Marshall script and brass knobs.",
    features: ["80W Class D Amplification", "Outward-Angled Tweeters for Wide Soundstage", "RCA, 3.5mm AUX, & Bluetooth 5.2", "Tactile Brass Control Knobs"],
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80"],
    pairs_with: ["STAT-GRV-01"],
  },
  {
    sku: "AUD-JBL-01",
    name: "JBL Charge 5 Portable Waterproof Bluetooth Speaker",
    category: "audio",
    subcategory: "speakers",
    tags: ["jbl", "speaker", "bluetooth", "waterproof", "portable", "outdoor", "sound"],
    price: 1499900,
    compare_at_price: 1799900,
    cost_price: 980000,
    currency: "INR",
    in_stock: true,
    stock_count: 35,
    low_stock_threshold: 6,
    description: "Take the party anywhere with IP67 waterproof and dustproof rating, separate tweeter with dual passive radiators, and built-in powerbank.",
    short_pitch: "Rugged IP67 waterproof outdoor speaker with 20-hour battery and phone-charging powerbank.",
    features: ["IP67 Waterproof & Dustproof", "20 Hours of Playtime", "Built-In Powerbank to Charge Devices", "JBL PartyBoost Multi-Speaker Pairing"],
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80"],
    pairs_with: ["LIFE-YET-01", "ACC-ANK-01"],
    upgrades_to: "AUD-MAR-01",
  },
  {
    sku: "AUD-SNH-01",
    name: "Sennheiser Momentum 4 Wireless ANC Headphones (60-Hour Battery)",
    category: "audio",
    subcategory: "headphones",
    tags: ["sennheiser", "headphones", "anc", "audiophile", "wireless", "audio"],
    price: 3499000,
    compare_at_price: 3999000,
    cost_price: 2450000,
    currency: "INR",
    in_stock: true,
    stock_count: 20,
    low_stock_threshold: 4,
    description: "Unmatched 60-hour battery life with Sennheiser's Signature Sound 42mm transducer system, adaptive noise cancellation, and lightweight fold-flat comfort.",
    short_pitch: "Class-leading 60-hour battery with 42mm audiophile-inspired transducer.",
    features: ["Massive 60-Hour Battery Life with Fast Charge", "42mm Audiophile-Inspired Acoustic System", "Adaptive Noise Cancellation & Transparency Mode", "Crystal-Clear 2x2 Beamforming Microphones"],
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80"],
    pairs_with: ["ACC-ANK-01"],
    upgrades_to: "AUD-APL-02",
  }
];;
